### ISSUE TITLE
Hey Thomas, I tried adding the ingredients  back in in. But did it do it correctly? are they working with the designated images?

### ISSUE THREAD

**Issue by katz0018** [katz0018/ecommerce-pattern-library#5]
Hey Thomas I tried re adding the ingredients list but I'm not sure if I did it correctly and how can I check. Do I have to ask Annie to check? 
@thomasjbradley

**Comment by thomasjbradley** [comment]
Can you commit & push the code so I can have a look?
It’s the `quantity-form.html` right?

**Comment by katz0018** [comment]
Did it work? it shows like there is nothing else to commit and push. Yes quantity form.html

**Comment by katz0018** [comment]
Also I heard about last night, CONGRATULATIONS! :)

**Comment by thomasjbradley** [comment]
@katz0018 Thanks!

I don’t see anything about ingredients in the code. Can you explain what you added?

**Comment by katz0018** [comment]
I added ingredients in each product > .md file and I tried adding so that depending the products the ingredients list will change, but im not sure it worked.

**Comment by katz0018** [comment]
Oh wait, I was in the wrong repository, maybe if you look now, it'll show up

**Comment by katz0018** [comment]
ohhh no, terminal keeps saying : 

<img width="571" alt="Screen Shot 2019-03-28 at 10 03 46 AM" src="https://user-images.githubusercontent.com/31801814/55163775-c9635d80-5140-11e9-866f-a8cd6062c87e.png">

and won't let me look at my local host or anything :(

**Comment by thomasjbradley** [comment]
The ingredients in the products look okay. Try changing this line here:
https://github.com/katz0018/ecommerce-pattern-library/blob/master/_patterns/forms/quantity-form.html#L19

Should be: `{{include.ingredients}}`

**Comment by katz0018** [comment]
Did it work? Im not sure how I can see if its working.

**Comment by thomasjbradley** [comment]
The code looks okay. I don’t think there’s any way for you to test it right now. But Annie can test it out in her branch. (After she does the “update from master” thing.)
